services:
  - type: web
    name: ia-sardinas-patterson
    env: python
    buildCommand: ""
    startCommand: python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
